### ISSUE TITLE
Add support for Bootstrap cards

### ISSUE THREAD

**Issue by norcalbiostat** [danielkvist/hugo-terrassa-theme#16]
I'd like to add a page for projects using the bootstrap card deck format. Is this feasible?

**Comment by dnlzrgz** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue #16](https://trello.com/c/px2CTGTh/3-issue-16)

**Comment by dnlzrgz** [comment]
Hi!

What you're asking for is not possible at the moment. Mainly because Terrassa does not have any type of support for Bootstrap.

But you can add your own CSS styles ([you can see how here if you want](https://github.com/danielkvist/hugo-terrassa-theme#custom-css)) if that's enough to solve your problem.

Sorry for the inconvenience.
