### ISSUE TITLE
Handling alternative font awesome icons in [params.social]

### ISSUE THREAD

**Issue by briggsy87** [danielkvist/hugo-terrassa-theme#24]
In the [params.social] section config.toml, I have added a new entry called donate, which is an external link to a donation page of sorts.

The icon itself is [here](https://fontawesome.com/icons/donate?style=solid) 

It seems like it is trying to render out the icon called donate from font awesome, but ends up showing the blinking exclamation mark, which signifies that it couldn't find that icon.

Any suggestions on how to add items other than what are already configured in the config.toml?

**Comment by dnlzrgz** [comment]
Hi @briggsy87!

The problem is that each item in the [params.social] configuration is rendered as:

```
<i class="fab fa-[social network]></i>
```

But the donate icon needs to have the class:

```
<i class="fas fa-donate"></i>
```

A solution would be to manually edit the file `footer_social.html` within the theme partials (`layouts/partials/footer_social.html`) and manually add the icon with its corresponding information just before the start of the loop that prints the other icons:

```
<div class="footer__social">
   <!-- Donate icon here -->
   <a href="[url]" class="footer__social__link" alt="[domain]" rel="noopener">
        <span>
            <i class="fas fa-donate"></i>
        </span>
    </a>
   <!-- End donate icon -->
    {{ range $k, $v := $items }}
    ...
```

I hope I helped you!
