### ISSUE TITLE
Unordered and ordered list

### ISSUE THREAD

**Issue by adamurban98** [danielkvist/hugo-terrassa-theme#26]
Could you please add some bullt points / numbers for ul and ol elements?

It seems that they get tranlated from markwon, but the included css of the team sets their list-style to none.

Is this on purpose?

**Comment by feministclickback** [comment]
Hi Ádám,

the theme uses <ul> and <li> for other layout elements like the header, which should not have bullets. This is why they are removed by default, and you have to bring bullets back in for the specific areas where you need them. (check posts like the About-page and any other page, they have bullets because they are enabled specifically for .post_body). 

Am I right in assuming you're trying to add bullets on the home page? Try adding this CSS to custom.css: 

`main.hero ul, .section ul {
  list-style-type: disc;
  margin-left: 10%;
}
`
`
main.hero ol, .section ol {
  list-style-type: decimal;
  margin-left: 5%;
}`

**Comment by dnlzrgz** [comment]
Hi @adamurban98. Is just as @feministclickback says.

Because the main menu is an unordered list the `list-style` property was set to `none`. This is actually a bad practice, and I'm sorry it got you into trouble.

A temporary solution if you don't want to modify the CSS styles as @feministclickback  says is to write some HTML in your markdown:

```
---
title: "Some post"
...
---

# Hello world

<ul style="list-style: inside">
    <li>Item</li>
    <li>Item</li>
</ul>
```

This should overwrite the CSS styles.
